### ISSUE TITLE
Map is not showing

### ISSUE THREAD

**Issue by kemhedge** [bkontonis/Plot-PostCodes-on-Interactive-Map-Using-Python#1]
Hello, after following your steps, everything seems to work except for the most important bit - the Map! The cell expands to the size specified but it is blank, no map, no scatter points. Would appreciate some help!

**Comment by bkontonis** [comment]
Hello kemhedge,

I just tried it and it works for me.
![image](https://user-images.githubusercontent.com/19557204/110603163-62091180-818f-11eb-9097-f4e0e7b1b4af.png)


I run it with Python 3.7.7 and below are the packages I use:
plotly==4.7.0
pgeocode==0.2.1
pandas==1.0.3
